name: DeathPenalty
version: '${version}'
main: link.harryw.deathpenalty.DeathPenalty
authors: [ EnderTweaks ]
description: A plugin to take money away from players on death.
depend: [ Vault ]
commands:
  dpreload:
    description: Reloads the config for DeathPenalty
    permission: deathpenalty.reload
permissions:
  deathpenalty.reload:
    description: Allows you to use /dpreload
  deathpenalty.bypass:
    description: Allows you to bypass the death penalty
