# ======================================
# DeathPenalty
# Created by EnderTweaks
# ======================================

#Message shown to person who died
deathMessage: "&cYou died and lost &l$%amount%&r&c!"
# percentage/fixed
lossType: "percentage"
#only used if lossType is percentage
percentageLost: 50
#only used if lossType is fixed
amountLost: 100
#Enable or disable the AccurateNode sponsor message
sponsorMessage: true