name: DeathPenalty
version: 1.1.0
description: A plugin to take money away from players on death.
api-version: 1.13
main: org.harrydev.deathpenalty.DeathPenalty
commands:
  dpreload:
    description: reloads the config
permissions:
  deathpenalty.reload:
    description: allows you to use /dpreload